package Space;

public enum AccionTurno {
    COMPRAR_NAVE,
    COMPRAR_CONSTRUCCION,
    COGER_MATERIAL,
    CONSTRUIR,
    MOVER_NAVE,
    ATACAR,
    TRANSPORTAR_CARGA,
    TRANSPORTAR_PERSONAS,
    MOSTRAR_INFORMACION_DE_PLANETAS,
    PASAR_TURNO,
    VERIFICAR_ELIMINACION,
    PASAR,
    CANCELADA;


}
